### ISSUE TITLE
cited page range may be just a single page number

### ISSUE THREAD

**Issue by Conal-Tuohy** [IsisCB/IsisCBLegacyDigitization#51]
need examples

**Comment by StephenPWeldon** [comment]
Here are some:

Review: http://conaltuohy.com/clients/isiscb/html/ISIS-01.html#p29-2.01
Review: http://conaltuohy.com/clients/isiscb/html/ISIS-01.html#p31-8.02
Article: http://conaltuohy.com/clients/isiscb/html/ISIS-01.html#p30-23
Article: http://conaltuohy.com/clients/isiscb/html/ISIS-01.html#p32-21

Stephen P. Weldon
Associate Professor of History of Science
Editor, Isis Bibliography of the History of Science
Department of History of Science
University of Oklahoma
601 Elm, Room 618
Norman, OK 73019-3106
website: stephenpweldon.com

**Comment by Conal-Tuohy** [comment]
Thanks Stephen!
